# ---------------------------------------------------
# ion-bump-on-tail.toml  (ion beam through stationary bulk)
# ---------------------------------------------------
# Setup:
#   - Bulk ions: stationary, physical mass (mp), cool (Ti << Te)
#   - Ion beam: +1 charge, mp, n_beam/n0 = 0.03, high drift v_ib, very cool
#   - Electrons: warm (same as before), tiny drift to make J ≈ 0
# Current neutralization:
#   v_e ≈ (n_beam / n_e) * v_ib ≈ (0.03 / 1.03) * v_ib ≈ 0.0291 * v_ib
# Here we pick v_ib = 0.05 c = 1.499e7 m/s → v_e ≈ 4.37e5 m/s
# ---------------------------------------------------

[input_parameters]
# -----------------------------
# species intrinsic properties (bulk species in the base plasma)
# -----------------------------
ion_mass_over_proton_mass = 1           # physical ions (protons)
ion_charge_over_elementary_charge = 1
electron_charge_over_elementary_charge = -1

# -----------------------------
# particle spatial distribution
# -----------------------------
random_positions_x = true
random_positions_y = false
random_positions_z = false
amplitude_perturbation_x = 0
amplitude_perturbation_y = 0
amplitude_perturbation_z = 0
wavenumber_electrons_x = 0
wavenumber_electrons_y = 0
wavenumber_electrons_z = 0
wavenumber_ions_x = 0
wavenumber_ions_y = 0
wavenumber_ions_z = 0

# ------------------------------
# electron velocity distribution (bulk electrons)
# ------------------------------
vth_electrons_over_c_x = 0.07071067812   # sqrt(2)*0.05 (same as your file)
vth_electrons_over_c_y = 0
vth_electrons_over_c_z = 0
electron_drift_speed_x = 4.37e5          # m/s; ≈ 0.0291 * v_ib with v_ib = 0.05c
electron_drift_speed_y = 0
electron_drift_speed_z = 0
velocity_plus_minus_electrons_x = false
velocity_plus_minus_electrons_y = false
velocity_plus_minus_electrons_z = false

# ------------------------------
# ion velocity distribution (bulk ions)
# ------------------------------
ion_drift_speed_x = 0                    # bulk stays put
ion_drift_speed_y = 0
ion_drift_speed_z = 0
ion_temperature_over_electron_temperature_x = 1.0e-3  # Ti << Te
ion_temperature_over_electron_temperature_y = 0
ion_temperature_over_electron_temperature_z = 0
velocity_plus_minus_ions_x = false
velocity_plus_minus_ions_y = false
velocity_plus_minus_ions_z = false

# ------------------------------
# domain, spacetime gridding (unchanged)
# ------------------------------
length = 1
grid_points_per_Debye_length = 2.565
timestep_over_spatialstep_times_c = 1.0
particle_BC_left  = 0
particle_BC_right = 0
field_BC_left  = 0
field_BC_right = 0

# ------------------------------
# other controls
# ------------------------------
print_info = true
relativistic = false
seed = 250724
tolerance_Picard_iterations_implicit_CN = 1e-6

# ------------------------------
# Ion beam population (positive, drifting, cool)
# weight_ratio = n_beam / n_bulk ≈ 0.03
# ------------------------------
[[species]]
mass_over_proton_mass = 1
charge_over_elementary_charge = 1
weight_ratio = 3e-2

# spatial distribution
random_positions_x = true
random_positions_y = false
random_positions_z = false
amplitude_perturbation_x = 0
amplitude_perturbation_y = 0
amplitude_perturbation_z = 0
wavenumber_perturbation_x = 0
wavenumber_perturbation_y = 0
wavenumber_perturbation_z = 0

# velocity distribution (pick high drift; very low thermal spread)
# v_ib = 0.05c = 1.499e7 m/s
vth_over_c_x = 5.0e-3         # very cool beam (adjust as you like)
vth_over_c_y = 0
vth_over_c_z = 0
drift_speed_x = 1.499e7       # m/s
drift_speed_y = 0
drift_speed_z = 0

# RNG control (optional; you can remove if not needed)
seed_position_override = true
seed_position = 10

[solver_parameters]
time_evolution_algorithm = 0
max_number_of_Picard_iterations_implicit_CN = 30
number_of_particle_substeps_implicit_CN = 2
number_grid_points = 40
field_solver = 0
number_pseudoelectrons = 40000
total_steps = 2000
number_pseudoparticles_species = [40000]   # one entry for the single ion-beam species

[external_magnetic_field]
path = "/Users/luis_lu/Desktop/UW-Madison/UWPlasma/aaron/JAX-in-Cell/external_fields/external_B_mirror.npz"
