# ---------------------------------------------------
# bump-on-tail-mirror.toml  (with external B mirror)
# ---------------------------------------------------

[input_parameters]
# -----------------------------
# species intrinsic properties
# -----------------------------
ion_mass_over_proton_mass = 1e9
ion_charge_over_elementary_charge = 1
electron_charge_over_elementary_charge = -1

# -----------------------------
# particle spatial distribution
# -----------------------------
random_positions_x = true
random_positions_y = false
random_positions_z = false
amplitude_perturbation_x = 0
amplitude_perturbation_y = 0
amplitude_perturbation_z = 0
wavenumber_electrons_x = 0
wavenumber_electrons_y = 0
wavenumber_electrons_z = 0
wavenumber_ions_x = 0
wavenumber_ions_y = 0
wavenumber_ions_z = 0

# ------------------------------
# electron velocity distribution
# ------------------------------
vth_electrons_over_c_x = 0.07071067812
vth_electrons_over_c_y = 0
vth_electrons_over_c_z = 0
electron_drift_speed_x = -2.25e6
electron_drift_speed_y = 0
electron_drift_speed_z = 0
velocity_plus_minus_electrons_x = false
velocity_plus_minus_electrons_y = false
velocity_plus_minus_electrons_z = false

# ------------------------------
# ion velocity distribution
# ------------------------------
ion_drift_speed_x = 0
ion_drift_speed_y = 0
ion_drift_speed_z = 0
ion_temperature_over_electron_temperature_x = 1e-9
ion_temperature_over_electron_temperature_y = 1e-9
ion_temperature_over_electron_temperature_z = 1e-9
velocity_plus_minus_ions_x = false
velocity_plus_minus_ions_y = false
velocity_plus_minus_ions_z = false

# ------------------------------
# domain, spacetime gridding
# ------------------------------
length = 1                          # meters
grid_points_per_Debye_length = 2.565
timestep_over_spatialstep_times_c = 1.0
particle_BC_left  = 0
particle_BC_right = 0
field_BC_left  = 0
field_BC_right = 0

# ------------------------------
# other controls
# ------------------------------
print_info = true
relativistic = false
seed = 250724
tolerance_Picard_iterations_implicit_CN = 1e-6

# ------------------------------
# Additional Maxwellian particle populations (2 species below)
# ------------------------------
[[species]]
mass_over_proton_mass = 0.0005446170199382714
charge_over_elementary_charge = -1
weight_ratio = 3e-2
random_positions_x = true
random_positions_y = false
random_positions_z = false
amplitude_perturbation_x = 0
amplitude_perturbation_y = 0
amplitude_perturbation_z = 0
wavenumber_perturbation_x = 0
wavenumber_perturbation_y = 0
wavenumber_perturbation_z = 0
vth_over_c_x = 0.07071067812
vth_over_c_y = 0
vth_over_c_z = 0
drift_speed_x = 7.5e7
drift_speed_y = 0
drift_speed_z = 0
seed_position_override = true
seed_position = 10

[[species]]
mass_over_proton_mass = 1e9
charge_over_elementary_charge = 1
weight_ratio = 3e-2
random_positions_x = true
random_positions_y = false
random_positions_z = false
amplitude_perturbation_x = 0
amplitude_perturbation_y = 0
amplitude_perturbation_z = 0
wavenumber_perturbation_x = 0
wavenumber_perturbation_y = 0
wavenumber_perturbation_z = 0
vth_over_c_x = 1e-100
vth_over_c_y = 1e-100
vth_over_c_z = 1e-100
drift_speed_x = 0
drift_speed_y = 0
drift_speed_z = 0
seed_position_override = true
seed_position = 10

# ------------------------------
# External magnetic field (constant in time)
# IMPORTANT:
#   Do NOT put a 'path = "...npz"' here, because that string enters the jitted
#   argument tree and JAX will error. Your driver should pre-load the NPZ and
#   replace this table with {"B" = (G,3) array}. For now, leave a placeholder.
# ------------------------------
[external_magnetic_field]
path = "/Users/luis_lu/Desktop/UW-Madison/UWPlasma/aaron/JAX-in-Cell/external_fields/external_B_mirror.npz"

[solver_parameters]
time_evolution_algorithm = 0
max_number_of_Picard_iterations_implicit_CN = 30
number_of_particle_substeps_implicit_CN = 2
number_grid_points = 40
field_solver = 0
number_pseudoelectrons = 40000
total_steps = 2000

# must have length == number of [[species]] blocks above (2)
number_pseudoparticles_species = [40000, 40000]
